### ISSUE TITLE
Make the API key a configuration

### ISSUE THREAD

**Issue by felipecassiors** [wakatime/vscode-wakatime#147] opened 2020-08-17 16:18 UTC
So we could let it be synced with the recently released VSCode Settings Sync.

Therefore, we would not need to provide it every time on new installations.

**Comment by alanhamlett** [comment] 2020-08-17 21:20
Duplicate of #44.

**Closed by alanhamlett** 2020-08-17 21:20 UTC

**Comment by felipecassiors** [comment] 2020-08-17 21:23
My bad.
