### ISSUE TITLE
WakaTime Initializing forever

### ISSUE THREAD

**Issue by CasterWx** [wakatime/vscode-wakatime#140] opened 2020-07-10 09:24 UTC
Wakatime is used in VS Code and idea in my computer , but WakaTime Initializing is always shown in VS Code, IDEA can be used normally.

![info.png](http://antzuhl.cn/upload/2020/7/info-ccf68dc097f9442b95aff837c68771e7.png)

**Comment by gandarez** [comment] 2020-07-13 13:55
Do you see anything logged into `~/.wakatime.log`?

**Comment by CasterWx** [comment] 2020-07-13 15:01
I saw my IDEA logs , then I closed IDEA, restart vscode,  no logs found.

**Comment by BobAnkh** [comment] 2020-07-21 14:24
Also face this problem in VSCode.

**Comment by BobAnkh** [comment] 2020-07-22 03:56
Well, after a very long period of time, it works fine.

**Comment by plusmultiply0** [comment] 2020-07-28 03:35
well, yesterday I also met the same problem.
wakatime on vscode is always initializing and I found nothing in my .wakatime.log.
I try to reinstall the extension several times but nothing change.
Here is my config except api_key, is there anything wrong?

debug = true
proxy = socks5://127.0.0.1:1080

**Comment by gandarez** [comment] 2020-07-28 10:26
> well, yesterday I also met the same problem.
> wakatime on vscode is always initializing and I found nothing in my .wakatime.log.
> I try to reinstall the extension several times but nothing change.
> Here is my config except api_key, is there anything wrong?
> 
> debug = true
> proxy = socks5://127.0.0.1:1080

Why are you using proxy on localhost?

**Comment by plusmultiply0** [comment] 2020-07-28 10:37
> > well, yesterday I also met the same problem.
> > wakatime on vscode is always initializing and I found nothing in my .wakatime.log.
> > I try to reinstall the extension several times but nothing change.
> > Here is my config except api_key, is there anything wrong?
> > debug = true
> > proxy = socks5://127.0.0.1:1080
> 
> Why are you using proxy on localhost?

because it will be hard for me to use wakatime without a proxy.
even without a proxy, the wakatime on vscode is always initializing.(of course, I try some ways like what I mentioned above)

However when the same config with proxy or with no proxy on IDEA, the wakatime can record my coding time.

**Comment by plusmultiply0** [comment] 2020-07-28 11:56
> > > well, yesterday I also met the same problem.
> > > wakatime on vscode is always initializing and I found nothing in my .wakatime.log.
> > > I try to reinstall the extension several times but nothing change.
> > > Here is my config except api_key, is there anything wrong?
> > > debug = true
> > > proxy = socks5://127.0.0.1:1080
> > 
> > 
> > Why are you using proxy on localhost?
> 
> because it will be hard for me to use wakatime without a proxy.
> even without a proxy, the wakatime on vscode is always initializing.(of course, I try some ways like what I mentioned above)
> 
> However when the same config with proxy or with no proxy on IDEA, the wakatime can record my coding time.

like BobAnkh , my wakatime on vscode after a very long period of time, it works fine. :sweat_smile:

**Comment by CasterWx** [comment] 2020-07-28 13:27
it's work fine,orz...

**Comment by strugglebak** [comment] 2020-07-28 15:17
same problem, wakatime version is the latest version(4.0.0), and vscode version is 1.47.3, on my mac os it works fine, somehow in win10 it doesn't work and stuck at "WakaTime Initializing...", could you please solve this problem ?

**Comment by strugglebak** [comment] 2020-07-28 15:18
> Well, after a very long period of time, it works fine.

a very long period of time??? how long is it ? 😂

**Comment by BobAnkh** [comment] 2020-07-28 15:22
> > Well, after a very long period of time, it works fine.
> 
> a very long period of time??? how long is it ? 😂

I don't know the exact time. Just leave it there for about an hour(or maybe longer?) and it works fine when I look up :joy:

**Comment by CasterWx** [comment] 2020-07-29 01:37
> > > Well, after a very long period of time, it works fine.
> > 
> > 
> > a very long period of time??? how long is it ? 😂
> 
> I don't know the exact time. Just leave it there for about an hour(or maybe longer?) and it works fine when I look up 😂

me too

**Comment by alanhamlett** [comment] 2020-07-30 02:32
Related to #144.

**Comment by strugglebak** [comment] 2020-07-30 06:14
> Related to #144.

I resolved this yestoday, by setting proxy configure on vscode-wakatime, here is my configuration

```
[settings]
api_key = xxx
debug = true
status_bar_coding_activity = true
status_bar_enabled = true
proxy = http://127.0.0.1:1080
```

**Comment by strugglebak** [comment] 2020-07-30 06:18
I think the plugin wants to download the wakatime-cli, and unzip it locally, if the network is unstable, so the process will stuck at "wakatime initializing", so all you need to do is to configure your local proxy, so that you can download the cli as fast as you can

**Comment by kritoke** [comment] 2020-08-03 14:38
If it is trying to download and unzip it locally, if the user uses something like NixOS or another kind of sandboxed environment, then they may not have write access as well.

**Comment by strugglebak** [comment] 2020-08-04 12:28
> If it is trying to download and unzip it locally, if the user uses something like NixOS or another kind of sandboxed environment, then they may not have write access as well.

I think may be you should give the vscode extension dir some access manually in this condition

**Comment by kritoke** [comment] 2020-08-04 12:37
Before knowing the proper Nix way of installing extensions, I ended up having to do a symbolic link to the currently installed wakatime cli in the vscode extensions folder (`~/.vscode/extensions/wakatime.vscode-wakatime-4.0.0/wakatime-cli/wakatime-cli`), since the extension appears to be hardcoded to look for the binary in a certain folder.  It would never download or unzip the wakatime-cli zip properly when installing in NixOS via the vscode extensions interface.  Probably would fix a number of things if the extension just did some kind of check for the executable in the path first or allow you to define the location that it was installed at.

**Comment by akshay-s-770** [comment] 2020-08-24 06:37
Its due to wakatime-cli.zip, it takes some hours to download. you should download it manual.
in my case i downloaded the zip manually and unzipped .vscode\extensions\wakatime.vscode-wakatime-4.0.5
I downloaded the zip from this URL https://wakatime-cli.s3-us-west-2.amazonaws.com/windows-x86-64/wakatime-cli.zip

**Comment by carlosanjos** [comment] 2020-08-24 09:47
Quoting @akshay-s-770 The macOS url is [https://wakatime-cli.s3-us-west-2.amazonaws.com/mac-x86-64/wakatime-cli.zip](https://wakatime-cli.s3-us-west-2.amazonaws.com/mac-x86-64/wakatime-cli.zip)

**Comment by veroiuxl** [comment] 2020-08-24 10:50
@akshay-s-770 Thanks, that worked!

**Comment by alanhamlett** [comment] 2020-08-24 14:23
Duplicate of #156, fixed in v4.0.5 which was released just now.

**Closed by alanhamlett** 2020-08-24 14:23 UTC
Labels: help wanted, question

**Comment by retampweb** [comment] 2023-04-14 06:40
have the same problem. Every time I save a document, waka time asks me to confirm the api key, even though it was saved before. reinstalling the plugin did not help.

**Comment by midstreeeam** [comment] 2023-07-23 07:55
problem still exist. I use wsl2, and it stuck at initializing, no `~/.wakatime.log` appear. Seems it still have problem downloading `wakatime-cli` since I found a zip with `0`byte inside `.wakatime/` folder. But manually download doesn't hlep (maybe i missed some operations)
