### ISSUE TITLE
multiple option in status bar

### ISSUE THREAD

**Issue by devbytemehedi** [wakatime/vscode-wakatime#364] opened 2023-09-12 14:22 UTC
![Code_cHmHE82l7V](https://github.com/wakatime/vscode-wakatime/assets/89072438/9204d1a1-189c-47dd-be43-57bc88604c0a)

## In this above picture you can see in the status bar there is 3 options at first i thought they do different things but they do nothing

**Comment by alanhamlett** [comment] 2023-09-13 13:34
Duplicate of #363.

**Closed by alanhamlett** 2023-09-13 13:34 UTC
