### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by mrcreel** [wakatime/vscode-wakatime#78] opened 2019-02-10 02:39 UTC
- Issue Type: `Performance`
- Extension Name: `vscode-wakatime`
- Extension Version: `1.2.5`
- OS Version: `Linux x64 4.15.0-45-generic`
- VSCode version: `1.31.0`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/michael/WakaTime.vscode-wakatime-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by alanhamlett** [comment] 2019-02-23 05:59
Duplicate of #83.

**Closed by alanhamlett** 2019-02-23 05:59 UTC
