### ISSUE TITLE
[WakaTime][ERROR] Invalid Api Key (104); Make sure your Api Key is correct!

### ISSUE THREAD

**Issue by AbhishekMaira10** [wakatime/vscode-wakatime#143] opened 2020-07-27 06:29 UTC
Error in the console:
[WakaTime][ERROR] Error: Command failed: c:\Users\abhim\.vscode\extensions\wakatime.vscode-wakatime-4.0.0\wakatime-cli\wakatime-cli.exe --file c:\Users\abhim\Documents\C++\InterviewBit\Array\maximum_sum_suarray.cpp --plugin "vscode/1.47.2 vscode-wakatime/4.0.0" --alternate-project C++ --config C:\Users\abhim\.wakatime.cfg --log-file C:\Users\abhim\.wakatime.log

**Comment by shawnlin0201** [comment] 2020-07-27 06:37
same here.
I checked path to `~/.wakatime.cfg`  and wakatime API Key is correct.

**Comment by hatoba29** [comment] 2020-07-27 07:09
Same here.
I checked API Key and path.
```
{
  "now": "2020/07/27 15:54:13 +0900",
  "version": "13.0.7",
  "plugin": "vscode/1.46.0 vscode-wakatime/4.0.0",
  "time": 1595832853.0465014,
  "caller": "wakatime/api.py",
  "lineno": 283,
  "file": null,
  "level": "DEBUG",
  "message": "{'response_code': 401, 'response_text': '{\"error\":\"Unauthorized\"}\\n'}"
}

```

**Comment by YouEclipse** [comment] 2020-07-27 07:12
same error From wakatime API too. 
wakatime-go is a go client

**Comment by beaukode** [comment] 2020-07-27 07:34
Same here
`{"now": "2020/07/27 09:32:54 +0200", "version": "13.0.7", "plugin": "vscode/1.47.2 vscode-wakatime/4.0.0", "time": 1595835173.3505187, "caller": "wakatime/api.py", "lineno": 339, "file": "/home/bk/.wakatime.log", "level": "WARNING", "message": "{'response_code': 401, 'response_content': '{\"error\":\"Unauthorized\"}\\n'}"}`

**Comment by ErickLuis00** [comment] 2020-07-27 07:45
Same here

**Comment by whtiehack** [comment] 2020-07-27 08:19
Same here

**Comment by vinurs** [comment] 2020-07-27 08:47
same here

**Comment by smrnjeet222** [comment] 2020-07-27 08:47
I am getting the same issue .
{"now": "2020/07/27 14:13:53 +0530", "version": "13.0.7", "plugin": "vscode/1.47.2 vscode-wakatime/4.0.0", "time": 1595839431.5994475, "caller": "wakatime\\api.py", "lineno": 339, "is_write": true, "file": "C:\\Users\\smrnj\\.wakatime.log", "level": "WARNING", "message": "{'response_code': 401, 'response_content': '{\"error\":\"Unauthorized\"}\\n'}"}

**Comment by summer20100514** [comment] 2020-07-27 09:32
same here

**Comment by v-zaburdaev** [comment] 2020-07-27 09:34
Same here

**Comment by octaviandd** [comment] 2020-07-27 09:35
same here

**Comment by abhagsain** [comment] 2020-07-27 09:40
I'm also having the same error

**Comment by jcruz97** [comment] 2020-07-27 09:42
I was wondering if I was the only one to have that issue :(

**Comment by Whis-dev** [comment] 2020-07-27 09:44
I have same error. so I change another api key but still have error.
I check .wakatime.cfg file and check $home root.
everything seems all right but still have error :(

**Comment by ApacheEx** [comment] 2020-07-27 09:50
looks like issue is more global than just vscode plugin

see https://github.com/wakatime/wakatime/issues/221

**Comment by AchalaSB** [comment] 2020-07-27 10:14
I'm also facing same issue. I guess its global issue. I'm getting same error in atom editor as well

**Comment by dyneskye** [comment] 2020-07-27 10:55
Same here I've been fiddling with it for ages then found this. Glad I'm not alone!

**Comment by technbuzz** [comment] 2020-07-27 10:58
Also on VSCode when I checked the log file it says "database is locked"

**Comment by RockiRider** [comment] 2020-07-27 12:31
Same here on VS Code

**Comment by kaka-ruto** [comment] 2020-07-27 12:33
Same here on Vim

**Comment by Bailey-1** [comment] 2020-07-27 12:37
Same on Xcode.

**Comment by niiccolas** [comment] 2020-07-27 12:54
Same here, despite a correct API key.

vscode status bar showing a "WakaTime Error" message:
![Screenshot 2020-07-27 at 14 50 07](https://user-images.githubusercontent.com/40167702/88543594-7fcaa180-d018-11ea-8362-f2be36e80fd2.jpg)

.wakatime.log last response message:
```json
{
  "now": "2020/07/27 14:46:59 +0200",
  "version": "13.0.7",
  "plugin": "vscode/1.47.2 vscode-wakatime/4.0.0",
  "time": 1595854016.701025,
  "caller": "wakatime/api.py",
  "lineno": 339,
  "file": "/Users/xyz/.wakatime.log",
  "level": "WARNING",
  "message": "{'response_code': 401, 'response_content': '{\"error\":\"Unauthorized\"}\\n'}"
}

```

VSCode 1.47.2
VSCode WakaTime extension 4.0.0
macOS 10.15.6

**Comment by PiotrJZielinski** [comment] 2020-07-27 13:10
On Ubuntu with deb and snap vscode - same error.

**Comment by nathanhenniges** [comment] 2020-07-27 13:14
Same here.  I even tried to reset the key and add the new one.  

`"level": "WARNING", "message": "{'response_code': 401, 'response_content': '{\"error\":\"Unauthorized\"}\\n'}"}`

**Comment by OlivierJM** [comment] 2020-07-27 13:16
+1

**Comment by sixsckert** [comment] 2020-07-27 13:26
Same issue on VSCode.

**Comment by igorskyflyer** [comment] 2020-07-27 13:51
I can confirm having the same issue in (regular) VS Code since today, checked everything, my API key is correct.

**Comment by joao-vieira** [comment] 2020-07-27 14:11
+1

**Comment by marceau-maubert** [comment] 2020-07-27 14:32
same here

**Comment by PiotrJZielinski** [comment] 2020-07-27 14:35
It seems the servers are fixed now

**Comment by alanhamlett** [comment] 2020-07-27 14:38
Sorry, this was me. 😭 I broke the api key parsing, but it's fixed now. The plugin saves your stats and syncs them up the next time the plugin runs (the next time you're typing) so nothing is lost, but still sorry about the frustration it may have caused.

**Closed by alanhamlett** 2020-07-27 14:38 UTC
