### ISSUE TITLE
WakaTime initializing...

### ISSUE THREAD

**Issue by Krausso** [wakatime/vscode-wakatime#160] opened 2020-08-25 14:41 UTC
Stuck on "**WakaTime initializing**". Already enabled debug mod, so it exactly stops on "**downloading wakatime-cli standalone**"

**Comment by alanhamlett** [comment] 2020-08-25 15:32
Duplicate of #156, please upgrade the plugin to v4.0.6 to fix this issue:

https://github.com/wakatime/vscode-wakatime/issues/156#issuecomment-679155558

**Comment by Krausso** [comment] 2020-08-25 17:31
Doesn't help, but ok. Gonna use WebStorm instead

**Comment by alanhamlett** [comment] 2020-08-25 17:54
After upgrading and reloading it's still stuck?

**Comment by Krausso** [comment] 2020-08-25 18:10
Yes

**Comment by alanhamlett** [comment] 2020-08-25 19:38
If you install the old v4.0.0 version does it finish initializing?

<img width="436" alt="Screen Shot 2020-08-23 at 6 44 29 PM" src="https://user-images.githubusercontent.com/522344/91219642-d090f100-e6cf-11ea-9312-c54ea4ef39fd.png">

**Comment by AndyYuan-Oni** [comment] 2020-08-26 07:20
Nope

**Comment by alanhamlett** [comment] 2020-08-26 14:31
@AndyYuan-Oni the last version that worked for you was 4.0.0 (https://wakatime.com/plugins/status) and @Krausso the last version working for you was 4.0.7. Either way, without an error message from vscode's dev console I'm stuck on how to fix this.

**Comment by montogeek** [comment] 2020-08-26 14:32
I unfortunately lost all my data from this week due to this bug, any solution to sync it?

**Comment by alanhamlett** [comment] 2020-08-26 14:43
@montogeek no, if the plugin didn't initialize then it won't track any time. It's best to get it initialized first so it can start tracking again. Have you tried re-installing v4.0.0 or manually downloading wakatime-cli and unzipping into the `~/.vscode/extensions/wakatime*/` folder? Here's wakatime-cli depending on your platform:
https://wakatime-cli.s3-us-west-2.amazonaws.com/linux-x86-64/wakatime-cli.zip
https://wakatime-cli.s3-us-west-2.amazonaws.com/mac-x86-64/wakatime-cli.zip
https://wakatime-cli.s3-us-west-2.amazonaws.com/windows-x86-32/wakatime-cli.zip
https://wakatime-cli.s3-us-west-2.amazonaws.com/windows-x86-64/wakatime-cli.zip

After it's working, I still haven't found out why it's not initializing for some. I'll need an error message or more info to figure it out.

**Comment by montogeek** [comment] 2020-08-26 14:54
I am afraid it is lost forever then, after updating the plugin version in VSCode it works again without any problem.

**Comment by Krausso** [comment] 2020-08-27 07:14
Okay, I fully reinstalled VS Code with all extensions few times and it somehow works.

**Comment by nerdpanda-ir** [comment] 2020-08-27 16:07
@alanhamlett  
thanks bro 
working for me

**Closed** 2020-08-28 15:15 UTC
