### ISSUE TITLE
extension host terminated unexpectedly

### ISSUE THREAD

**Issue by Nihileon** [wakatime/vscode-wakatime#52] opened 2018-05-06 01:38 UTC
when i use enable this extension, vscode show me that extension host terminated unexpectedly

**Comment by MasihIT** [comment] 2018-06-09 17:30
When i don't have any connection to the internet, I get the same message!

**Comment by alanhamlett** [comment] 2018-06-09 18:02
If I start VS Code without internet I get this error in the Console window:
```
  ERR getaddrinfo ENOTFOUND github.com github.com:443: Error: getaddrinfo ENOTFOUND github.com github.com:443
	at errnoException (dns.js:28:10)
	at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
```

Or if internet connection is lost while coding:
```
[Extension Host] [WakaTime] [ERROR] Error: Command failed: pythonw /Users/alan/.vscode/extensions/WakaTime.vscode-wakatime-1.2.2/out/wakatime-master/wakatime/cli.py --file /Projects/vscode-wakatime/package.json --plugin vscode/1.23.1 vscode-wakatime/1.2.2
[Extension Host] [WakaTime] [WARN] API Error (102); Check your /Users/alan/.wakatime.log file for more details.
```

I'm not able to reproduce the `extension host terminated unexpectedly` message.

**Comment by Abhinickz** [comment] 2018-06-29 19:31
This error show even if the Internet is connected.
The same error was happening logged on issue : https://github.com/wakatime/vscode-wakatime/issues/49.
which was never resolved and was closed without giving any information!!

**Comment by gandarez** [comment] 2019-04-15 14:17
duplicate of https://github.com/wakatime/vscode-wakatime/issues/49

**Closed by gandarez** 2019-04-15 14:17 UTC
