### ISSUE TITLE
how to uninstall all things?

### ISSUE THREAD

**Issue by zhangwilling** [wakatime/vscode-wakatime#85] opened 2019-03-05 09:03 UTC
Recently, wakatime not work, just intiallizeing.
 i manually remove  .wakatime.db    .wakatime.log  .wakatime.cfg and uninstall wakatime plugin, then reinstall wakatime plugin. But, it not works still intiallizeing. 

i found the sqlite db was not  created.

i guess i did  not remove all things, so reinstall not worked.

**Comment by alanhamlett** [comment] 2019-03-06 09:19
https://wakatime.com/plugins/vs-code/uninstalling

Closing as duplicate of #84.

**Closed by alanhamlett** 2019-03-06 09:19 UTC
