### ISSUE TITLE
Turn the extension an UI kind

### ISSUE THREAD

**Issue by felipecassiors** [wakatime/vscode-wakatime#148] opened 2020-08-17 16:22 UTC
Extensions of the UI kind are installed in the host running VSCode and not in the remote hosts (WSL, SSH, and containers/codespaces). Therefore they are always enabled, no matter which remote you're connected to. 

Is it possible to turn this extension into a UI kind? I'm not sure if all the needed features are available as a UI extension, with no access to the workspace, hopefully you can still figure out the language of the currently opened file.

**Comment by alanhamlett** [comment] 2020-08-17 21:26
Unfortunately, UI extensions are only for themes, snippets, language grammars, and keymaps. The WakaTime plugin needs to read the file opened in the workspace in order to detect project and language, and UI extensions don't allow access to the files in the workspace.

Closing as duplicate of #130.

**Closed by alanhamlett** 2020-08-17 21:26 UTC

**Comment by felipecassiors** [comment] 2020-08-17 21:27
I see, thank you.

**Comment by alanhamlett** [comment] 2020-08-17 23:07
Also related to https://github.com/wakatime/vscode-wakatime/issues/95#issuecomment-675158338
