### ISSUE TITLE
supported github web extensions

### ISSUE THREAD

**Issue by underwindfall** [wakatime/vscode-wakatime#241] opened 2021-10-21 20:52 UTC
wakatime is great plugin for **vscode desktop version**, however since github support **WEB IDE**,  could you consider adding this feature to suppor it ?
More infomation is here
https://code.visualstudio.com/api/extension-guides/web-extensions

**Comment by alanhamlett** [comment] 2021-12-25 03:42
Duplicate of #237.

**Closed by alanhamlett** 2021-12-25 03:42 UTC
