### ISSUE TITLE
Continuously invoked on GitHub Codespaces

### ISSUE THREAD

**Issue by linbudu599** [wakatime/vscode-wakatime#169] opened 2020-10-27 06:54 UTC
When using in GitHub Codespaces, I cannot close dialog which required `WakaTime API Token`, even if I tap `escape`, it would appear again after seconds until I enter the correct token.

**Comment by JipFr** [comment] 2021-05-05 12:22
I'm experiencing this as well

**Comment by alanhamlett** [comment] 2021-05-05 14:05
Should be fixed with v6.0.4. However, can you share the error message from your vscode dev console window with me before upgrading the plugin?

**Comment by JipFr** [comment] 2021-05-10 09:59
Apologies for the late response. I am currently on 8.0.0 and am still getting it. The error is as follows:
![Screenshot 2021-05-10 at 11 59 19](https://user-images.githubusercontent.com/17685409/117642045-2ab2e300-b187-11eb-8c51-d5b4e3243df6.png)

**Comment by alanhamlett** [comment] 2021-12-26 14:24
Let's move this into #244.

**Comment by TheDevMinerTV** [comment] 2023-08-24 09:11
This is still happening.

**Comment by alanhamlett** [comment] 2023-08-25 13:04
Let's discuss in #362.

**Closed by alanhamlett** 2023-08-25 13:04 UTC

**Comment by alanhamlett** [comment] 2024-03-22 16:32
A duplicate of #1035? I can't reproduce this for some reason... it saves the api key and never asks again for me as long as I'm using the same codespace and not a new one.

**Comment by alanhamlett** [comment] 2024-03-23 12:52
We have too many issues open for this. Locking this and moving discussion to #362.
