### ISSUE TITLE
Why I put API key correct but it still show pop-up fill api key

### ISSUE THREAD

**Issue by CNDvn** [wakatime/vscode-wakatime#264] opened 2022-02-24 12:39 UTC
![image](https://user-images.githubusercontent.com/63216927/155525591-9bd7ed0a-63de-42d3-a12d-fb06522d89c0.png)

**Comment by anhzf** [comment] 2022-02-24 13:00
> ![image](https://user-images.githubusercontent.com/63216927/155525591-9bd7ed0a-63de-42d3-a12d-fb06522d89c0.png)

I'm facing with this issue too lastly. I'll temporary disable this extension.

**Comment by riflowth** [comment] 2022-02-24 13:30
Me too. I'm facing with this issue after press `save` (ctrl+s)

**Comment by ineshbose** [comment] 2022-02-24 15:37
Having the same issue here!

**Comment by alanhamlett** [comment] 2022-02-24 19:43
This is happening because Windows Defender is blocking wakatime-cli from running https://github.com/wakatime/wakatime-cli/issues/660
Allowing wakatime-cli to run should fix it, but I'm wondering if Windows Defender is causing wakatime-cli to exit with code `104`. That would cause the vscode-wakatime plugin to show an api key error, but wouldn't prompt for your api key:
https://github.com/wakatime/vscode-wakatime/blob/2dd495925ac127985d7a960797285f31b01d4958/src/wakatime.ts#L442

Maybe Defender is also blocking vscode from reading your api key from `~/.wakatime.cfg` when it blocks wakatime-cli.

Can you please run this command:
`~/.wakatime/wakatime-cli --help`
Then let me know the exit code:
`echo Exit Code is %errorlevel%`

My guess is Windows Defender is somehow blocking vscode from reading your api key, as a side effect from detecting the wakatime plugin as a malware false positive.

**Comment by alanhamlett** [comment] 2022-02-24 19:45
Closing as duplicate of #262.

**Closed by alanhamlett** 2022-02-24 19:45 UTC
