### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by 12-mundo** [wakatime/vscode-wakatime#127] opened 2020-03-12 19:14 UTC
- Issue Type: `Performance`
- Extension Name: `vscode-wakatime`
- Extension Version: `4.0.0`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.43.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\RaymundoDG\WakaTime.vscode-wakatime-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by gandarez** [comment] 2020-03-12 20:01
Please attach the `cpu profile` file.

**Comment by ppizarror** [comment] 2020-03-25 15:45
Can confirm this issue too. When wakatime enabled replacing a string in a large number of files (>1000) causes wakatime to create hundreds of "wakatime-cli" process, raising CPU usage to 100% and RAM usage to 100% too

**Comment by ppizarror** [comment] 2020-03-25 15:45
> Can confirm this issue too. When wakatime enabled replacing a string in a large number of files (>1000) causes wakatime to create hundreds of "wakatime-cli" process, raising CPU usage to 100% and RAM usage to 100% too

I had to disable the plugin in order to continue working

**Comment by alanhamlett** [comment] 2020-03-25 16:45
If you add this line to your `~/.wakatime.cfg` file then restart vscode, does it get better?

`standalone = false`

**Comment by simonemike95** [comment] 2020-03-27 19:18
Also happening to me with almost zero reproducibility. Some days it will happen every hour, other times I won't see it for days. Will be trying the suggestion above to see if it helps.

**Comment by alanhamlett** [comment] 2021-05-05 21:50
Probably fixed in v7.0.0 of the vscode extension, now that we're using the new [wakatime-cli](https://github.com/wakatime/wakatime-cli) that removes the Python dependency.

**Closed by alanhamlett** 2021-05-05 21:50 UTC
Labels: invalid

**Comment by alanhamlett** [comment] 2023-12-05 23:34
😆  I can't help but laugh because the definition of [shady](https://www.google.com/search?q=define%3Ashady) means what's happening is hidden from you while the [wakatime-cli source code](https://github.com/wakatime/wakatime-cli) can be easily viewed.

Seriously, I wish we could reproduce this and fix it. This was last month, so you might have been using a version where we tried detecting language from the file contents, which was taking too much CPU resources. We reverted it last month with [v1.86.2](https://github.com/wakatime/wakatime-cli/releases/tag/v1.86.2) so would be worth checking if it's still causing high cpu load.
