### ISSUE TITLE
Wakatime terminal: unusual coding activity

### ISSUE THREAD

**Issue by dmig** [wakatime/vscode-wakatime#193] opened 2021-05-17 07:32 UTC
During the past week Wakatime report shows almost 75 hours of activity in the terminal. Which is definitely invalid.

Version: 1.0.0 with cli 13.1.0

```
Bash
Last Seen: 4 minutes ago
Version: 1.0.0 with cli 13.1.0
```

![Screenshot from 2021-05-17 09-28-59](https://user-images.githubusercontent.com/388564/118448665-94387180-b6f2-11eb-82a4-a05ed7bb55db.png)

**Comment by alanhamlett** [comment] 2021-09-17 00:38
Duplicate of #163

**Closed by alanhamlett** 2021-09-17 00:38 UTC
