### ISSUE TITLE
Unusual coding activity from  VS Code WakaTime plugin

### ISSUE THREAD

**Issue by sourav-ojha** [wakatime/vscode-wakatime#198] opened 2021-05-20 03:06 UTC
## Here are list of extension I m using in my VS code.
1) Bracket pair colorizer
2) Code TIme
3) EJS language support
4) ES7 React/Redux
5) GitLens
6) Live Server
7) npm Intellisense
8) Prettier
9) Waka Time
10) ES Lint
11) Visual Studio Intellicode

**Comment by VR314** [comment] 2021-07-13 11:45
The output of running `code-insiders --list-extensions`
```
Extensions installed on WSL: Ubuntu-20.04:
- apollographql.vscode-apollo
- burkeholland.simple-react-snippets
- DavidAnson.vscode-markdownlint
- dbaeumer.vscode-eslint
- eamodio.gitlens
- esbenp.prettier-vscode
- GraphQL.vscode-graphql
- Gruntfuggly.todo-tree
- ms-python.python
- ms-python.vscode-pylance
- ms-toolsai.jupyter
- naumovs.color-highlight
- pnp.polacode
- ritwickdey.LiveServer
- sburg.vscode-javascript-booster
- WakaTime.vscode-wakatime
- yzhang.markdown-all-in-one
- zenclabs.reactpreview
```

**Comment by alanhamlett** [comment] 2021-09-17 00:37
Duplicate of #163.

**Closed by alanhamlett** 2021-09-17 00:37 UTC

**Comment by gitofdw** [comment] 2023-10-02 03:51
2gua.rainbow-brackets
aaron-bond.better-comments
akamud.vscode-theme-onedark
brainfit.vscode-importmagic
christian-kohler.path-intellisense
dongli.python-preview
donjayamanne.githistory
eamodio.gitlens
edwardhjp.vscode-author-generator
formulahendry.code-runner
formulahendry.terminal
frhtylcn.pythonsnippets
garytyler.darcula-pycharm
GitHub.copilot
GitHub.copilot-chat
golang.go
hediet.vscode-drawio
intellsmi.comment-translate
jebbs.plantuml
JuanBlanco.solidity
k--kato.intellij-idea-keybindings
KevinRose.vsc-python-indent
LeetCode.vscode-leetcode
magicstack.MagicPython
mechatroner.rainbow-csv
mhutchie.git-graph
ms-python.isort
ms-python.python
ms-python.vscode-pylance
ms-toolsai.jupyter
ms-toolsai.jupyter-keymap
ms-toolsai.jupyter-renderers
ms-toolsai.vscode-jupyter-cell-tags
ms-toolsai.vscode-jupyter-slideshow
mycelo.embrace
njpwerner.autodocstring
njqdev.vscode-python-typehint
OBKoro1.korofileheader
oderwat.indent-rainbow
RemixProject.ethereum-remix
Shan.code-settings-sync
shd101wyy.markdown-preview-enhanced
slevesque.vscode-hexdump
steoates.autoimport
streetsidesoftware.code-spell-checker
tht13.python
tintinweb.graphviz-interactive-preview
tintinweb.solidity-visual-auditor
tintinweb.vscode-ethover
tintinweb.vscode-inline-bookmarks
tintinweb.vscode-solidity-flattener
tintinweb.vscode-solidity-language
uctakeoff.vscode-counter
VisualStudioExptTeam.intellicode-api-usage-examples
VisualStudioExptTeam.vscodeintellicode
vscode-icons-team.vscode-icons
WakaTime.vscode-wakatime
wayou.vscode-todo-highlight
zhuangtongfa.material-theme
zxh404.vscode-proto3

**Comment by Aatmaj-Zephyr** [comment] 2024-09-07 04:55
**Output of  code --list-extensions**
076923.python-image-preview
aaron-bond.better-comments
adam-bender.commit-message-editor
aessoft.aessoft-class-autocomplete
ahadcove.js-quick-console
akamud.vscode-javascript-snippet-pack
alefragnani.bookmarks
alefragnani.project-manager
amazonwebservices.amazon-q-vscode
amazonwebservices.aws-toolkit-vscode
anfuchs.alexa-code-snippets
ask-toolkit.alexa-skills-kit-toolkit
batisteo.vscode-django
be5invis.vscode-custom-css
cameron.vscode-pytest
christian-kohler.path-intellisense
codacy-app.codacy
codezombiech.gitignore
continue.continue
cstrap.python-snippets
ctcuff.font-preview
cweijan.vscode-office
dbaeumer.vscode-eslint
donjayamanne.githistory
donjayamanne.python-environment-manager
eamodio.gitlens
ecmel.vscode-html-css
electreefrying.auto-import
electreefrying.drag-import-relative-path
esbenp.prettier-vscode
figma.figma-vscode-extension
formulahendry.auto-close-tag
formulahendry.auto-rename-tag
geometricapplications.reline
georgewfraser.vscode-javac
github.remotehub
github.vscode-github-actions
github.vscode-pull-request-github
gruntfuggly.todo-tree
haihua.tdd-snippets
hbenl.vscode-test-explorer
hediet.vscode-drawio
huyigong.vscode-latex-commands
ionutvmi.path-autocomplete
iuripavani.python-uml
jairhenrique.pytest-snippets
james-yu.latex-workshop
jeffersonqin.latex-snippets-jeff
jithurjacob.nbpreviewer
johnpapa.vscode-peacock
kameshkotwani.google-search
kisstkondoros.vscode-gutter-preview
leodevbro.blockman
liviuschera.noctis
maltehei.latex-citations
mathematic.vscode-latex
mathworks.language-matlab
mechatroner.rainbow-csv
michaelcurrin.auto-commit-msg
michelemelluso.gitignore
mintlify.document
mmabt.jvsnip
mrmlnc.vscode-attrs-sorter
ms-azuretools.vscode-docker
ms-dotnettools.csharp
ms-dotnettools.vscode-dotnet-runtime
ms-python.autopep8
ms-python.debugpy
ms-python.python
ms-python.vscode-pylance
ms-toolsai.jupyter
ms-toolsai.jupyter-keymap
ms-toolsai.jupyter-renderers
ms-toolsai.vscode-jupyter-cell-tags
ms-toolsai.vscode-jupyter-slideshow
ms-vscode-remote.remote-containers
ms-vscode-remote.remote-ssh
ms-vscode-remote.remote-ssh-edit
ms-vscode-remote.vscode-remote-extensionpack
ms-vscode.cpptools
ms-vscode.cpptools-extension-pack
ms-vscode.cpptools-themes
ms-vscode.live-server
ms-vscode.remote-explorer
ms-vscode.remote-repositories
ms-vscode.remote-server
ms-vscode.test-adapter-converter
ms-vscode.vscode-serial-monitor
mutantdino.resourcemonitor
nicholashsiang.vscode-javascript-snippet
njpwerner.autodocstring
oderwat.indent-rainbow
oouo-diogo-perdigao.docthis
paulmolluzzo.convert-css-in-js
pranaygp.vscode-css-peek
qwtel.sqlite-viewer
rangav.vscode-thunder-client
redhat.java
ritwickdey.liveserver
sabertazimi.latex-snippets
sidthesloth.html5-boilerplate
solnurkarim.html-to-css-autocompletion
sswatson.table-editor
streetsidesoftware.code-spell-checker
tabnine.tabnine-vscode
tchojnacki.cpp-compile
tecosaur.latex-utilities
tomoki1207.pdf
torresgol10.bootstrap-class-autocomplete
trunk.io
tushortz.java-snippets
visualstudioexptteam.intellicode-api-usage-examples
visualstudioexptteam.vscodeintellicode
visualstudioexptteam.vscodeintellicode-completions
vsciot-vscode.vscode-arduino
vscjava.vscode-java-debug
vscjava.vscode-java-dependency
vscjava.vscode-java-pack
vscjava.vscode-java-test
wakatime.vscode-wakatime
wscats.html-snippets
wscats.java-snippet
xabikos.javascriptsnippets
yongke.latex-wordcount
yutengjing.open-in-external-app
yzhang.markdown-all-in-one
zignd.html-css-class-completion

**Comment by sam98brown** [comment] 2024-09-09 09:29
`aaron-bond.better-comments
alefragnani.project-manager
anthonydiametrix.acf-snippet
astro-build.astro-vscode
atlassian.atlascode
binarybytes.snippets
britesnow.vscode-toggle-quotes
browserstackcom.browserstack-vscode
chakrounanas.turbo-console-log
christian-kohler.npm-intellisense
christian-kohler.path-intellisense
codezombiech.gitignore
daylerees.rainglow
dbaeumer.vscode-eslint
devsense.composer-php-vscode
devsense.intelli-php-vscode
devsense.phptools-vscode
devsense.profiler-php-vscode
donjayamanne.git-extension-pack
donjayamanne.githistory
eamodio.gitlens
ecmel.vscode-html-css
editorconfig.editorconfig
emilast.logfilehighlighter
equinusocio.vsc-material-theme-icons
esbenp.prettier-vscode
firefox-devtools.vscode-firefox-debug
formulahendry.auto-rename-tag
github.vscode-github-actions
huuums.vscode-fast-folder-structure
ionutvmi.path-autocomplete
jeremyljackson.vs-docblock
johnbillion.vscode-wordpress-hooks
lukebatchelor.code-bitbucket-pipelines
mblode.twig-language-2
mrmlnc.vscode-scss
ms-python.debugpy
ms-python.python
ms-python.vscode-pylance
ms-vscode.cpptools
ms-vscode.cpptools-extension-pack
ms-vscode.cpptools-themes
ms-vscode.vscode-serial-monitor
neilbrayfield.php-docblocker
octref.vetur
onecentlin.laravel-blade
onecentlin.laravel5-snippets
pulkitgangwar.nextjs-snippets
redhat.vscode-commons
redhat.vscode-yaml
ritwickdey.liveserver
ronvanderheijden.phpdoc-generator
rubymaniac.vscode-paste-and-indent
shufo.vscode-blade-formatter
shyykoserhiy.vscode-spotify
simonsiefke.svg-preview
sourcegraph.cody-ai
stylelint.vscode-stylelint
syler.sass-indented
usernamehw.errorlens
vue.volar
wakatime.vscode-wakatime
whatwedo.twig
wix.vscode-import-cost
xdebug.php-debug
yoavbls.pretty-ts-errors
ziyasal.vscode-open-in-github`
