### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by michaelwnau** [wakatime/vscode-wakatime#298] opened 2022-09-09 19:17 UTC
- Issue Type: `Bug`
- Extension Name: `vscode-wakatime`
- Extension Version: `19.1.0`
- OS Version: `Windows_NT x64 10.0.22000`
- VS Code version: `1.71.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

After updating to v.19.1.0,, the coding daily time clock view has disappeared from the toolbar in VS Code. Current ver. of VS Code, Win. 11. Verified personal API in .cfg but extension is hung in "initialized."

**Comment by alanhamlett** [comment] 2022-09-09 21:45
Duplicate of #297.

**Closed by alanhamlett** 2022-09-09 21:45 UTC
