### ISSUE TITLE
Invalid api key error in VScode

### ISSUE THREAD

**Issue by jeetsdev** [wakatime/vscode-wakatime#260] opened 2022-02-01 11:02 UTC
I am getting an invalid API key error after almost every 24 hours. I am setting the API key again then it's working for some hours and again I am getting the same issue.

Here's the log output ...

```jsn
{"caller":"/home/runner/work/wakatime-cli/wakatime-cli/cmd/run.go:240","func":"runCmd","level":"error","message":"failed to run command: sending heartbeat(s) failed: invalid api key... find yours at wakatime.com/api-key. failed to load command parameters: failed to load api params: failed to load api key","now":"2022-02-01T16:22:16+05:30","version":"v1.35.1"}
```

**Comment by alanhamlett** [comment] 2022-02-01 22:19
Duplicate of #256.

**Closed by alanhamlett** 2022-02-01 22:19 UTC
