### ISSUE TITLE
WakaTime showing error on initializing :(

### ISSUE THREAD

**Issue by AssassinAguilar** [wakatime/vscode-wakatime#204] opened 2021-05-26 16:06 UTC
Whenever I open my vs code to do some work then wakatime shows error on initializing then it starts to show wakatime error at the place of wakatime initializing and shows Unknown Error check ``` File Path/.wakatime.log``` even there's no file with his name at that location in my device  :( please healp me

**Comment by alanhamlett** [comment] 2021-05-26 16:16
Please turn on [Debug mode](https://github.com/wakatime/vscode-wakatime#troubleshooting) then check your vscode Dev Console for an error message. Also, try adding this line to your `~/.wakatime.cfg` file:

`legacy_python_cli = false`

**Comment by AssassinAguilar** [comment] 2021-05-27 04:38
@alanhamlett ok after doing what you said I am still getting same errors and in dev console. it still shows the same error which I tell above nothing new happens, it still tells to check the ```~/.wakatime.log``` file even there's no file like that in my laptop

**Comment by alanhamlett** [comment] 2021-05-27 15:29
Would you like to video chat so I can help resolve this faster? You may email me alan@wakatime.com so we can setup a time that's good for you.

**Comment by AssassinAguilar** [comment] 2021-05-27 15:56
Sorry sir but I am a kid so my parents don't allow me and I also don't like to be much social 😅 I can send a video recording if you want of the dev Console in my vs code and ```.wakatime.log``` file and ```.wakatime.cfg``` file

**Comment by AssassinAguilar** [comment] 2021-05-28 05:41
Well @alanhamlett sir I think I found the main problem I found out a URL in my ```~/.wakatime.log``` file which is appearing in my laptop now which leads me to a page where it says no start date found so I think the heartbeats aren't getting send due to that

**Comment by alanhamlett** [comment] 2021-05-28 15:47
Duplicate of #415.

**Closed by alanhamlett** 2021-05-28 15:47 UTC
