### ISSUE TITLE
Extension crash and cause all other extensions to crash

### ISSUE THREAD

**Issue by mazensharkawy** [wakatime/vscode-wakatime#60] opened 2018-07-20 21:07 UTC
Whenever i open vscode i get Extension Host terminated unexpectedly
I know there's a similar issue and i tried the solution discussed there.. to remove the trailing semicolon in the environment path.
I also tried deleting the .cfg file, re-installing the plugin, re-installing vscode.
It's also worth mentioning that when I try to enter api key i get wakatime.apikey is not found.
![](https://user-images.githubusercontent.com/24762902/42837367-349b6512-89fe-11e8-81fd-c4668c31d41a.png)

**Comment by gandarez** [comment] 2019-04-15 14:19
duplicate of https://github.com/wakatime/vscode-wakatime/issues/49

**Closed by gandarez** 2019-04-15 14:19 UTC
