### ISSUE TITLE
Ignoring valid heartbeats when using 'SSH FS' extension

### ISSUE THREAD

**Issue by adamemrts** [wakatime/vscode-wakatime#117] opened 2019-10-31 08:39 UTC
When using 'SSH FS' Vscode extension, all heartbeats are ignored 'cause Wakatime extension can't find a file and therefore exclude that heartbeats from sending.
Maybe there is a way to include this heartbeats like any others? All debug info, even file path is correct, just excluded 'cause it's 'virtual/remote' file and can't be found on disc.

Example debug log:
`
{"now": "2019/10/30 00:50:11 +0100", "version": "13.0.1", "plugin": "vscode/1.39.2 vscode-wakatime/2.2.1", "time": 1572393011.7977805, "caller": "/home/xxx/.vscode-oss/extensions/wakatime.vscode-wakatime-2.2.1/wakatime-master/wakatime/main.py", "lineno": 61, "file": "/xxx/xxx/xxx.less", "level": "DEBUG", "message": "File does not exist; ignoring this heartbeat."}
`

**Comment by alanhamlett** [comment] 2019-10-31 15:11
This is related to #67. We need to add support for reading remote files to https://github.com/wakatime/wakatime.

**Comment by alanhamlett** [comment] 2021-12-26 14:06
Duplicate of #67.

**Closed by alanhamlett** 2021-12-26 14:06 UTC
Labels: help wanted

**Comment by alanhamlett** [comment] 2022-01-07 16:25
Related to wakatime/wakatime-cli#623, which added support for `ssh://` and `sftp://` remote files.
